### ISSUE TITLE
Error Install

### ISSUE THREAD

**Issue by zufan-yp** [amd64fox/SpotX#137]
### 🧐 Have you read the FAQ and viewed similar issues?

- [ ] I have read the FAQ
- [X] I have checked older issues, open and closed
- [ ] I did a clean install of SpotX as <a href="https://github.com/amd64fox/SpotX/discussions/111#discussion-4304353">described in the FAQ</a>

### Сountry of your account

Indonesia

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for Windows
1.1.93.896.g3ae3b4f3
- Windows: Windows 11
- PowerShell: 5.1.22000.832
```

### 📝 Description

I have tried to install and re-install the error appears in the attached image. when spotify is run Ads still appear every time you play a song from 1-4 songs. Is this just happening to me?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/78656480/189474541-99de13da-e9a1-41fa-97a1-74e9f6c7f326.png)

**Comment by amd64fox** [comment]
Why are you ticking that you read the FAQ?

**Comment by zufan-yp** [comment]
Done solved thx

![image](https://user-images.githubusercontent.com/78656480/189476735-7b0fdb72-3404-473a-975a-b0c45770aa38.png)
