### ISSUE TITLE
[request] supporting classic ui

### ISSUE THREAD

**Issue by c4ttysam** [amd64fox/SpotX#379]
### Description of the new feature / enhancement

hi there, is it possible to support the classic UI (last found working version 1.1.39.612).
the UI before mobilized ones was pretty good as an actual desktop app. 

there's an repository which had hosted it
https://github.com/Hippityy/spotify-old-ui
seems version after that no longer supports reverting the ui.

also blockthespot works well with this version (used 2020 mar release).

can it be possible to have this for spotx, specifically for this version and have things decluttered (something like hiding upgrade button, possible things corresponding to latest release). 

### 📸 Screenshots

![th-3876603000](https://user-images.githubusercontent.com/127286831/232274416-2db6f746-dbd3-43be-818c-812fc30cd91d.jpg)

### ⠀

***
If you like the idea, add a 👍 reaction to this post

**Comment by amd64fox** [comment]
SpotX does not support this old interface, especially since [it will be shut down](https://github.com/amd64fox/SpotX/issues/374) soon.
